mysql:
  image: mysql
  environment:
    - MYSQL_DATABASE=surveydb
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
  ports:
    - 3306:3306

web:
  build: .
  dockerfile: DevDockerfile
  volumes:
    - .:/usr/src/app
  environment:
    - DEBUG=sumoqs:server
    - SESSION_SECRET=sumoqs-has-a-secret
  ports:
    - 80:3000
  links:
    - mysql
